# .readthedocs.yaml
version: 2

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs 

build:
  os: ubuntu-22.04
  tools:
    python: "3.12" 
  jobs:
    post_checkout:
      - echo "Post checkout"